## Worflow for PRECISE Data in restructured format

This workflow is for the PRECISE ANC surveillance data in the final format (restructured) which will be used for future data sharing.
Combined ANC surveillance data for all 3 sites (Gambia, Kenya and Mozambique) for all visits is contained in a single file

In [1]:
%load_ext autoreload
%autoreload 2

In [93]:
import os
from DataAnalyst_v3.precise import Precise

In [4]:
root_dir=r"surveillance"

In [94]:
gambia=Precise("Gambia", os.path.join(root_dir, "PRECISE_data_request_2024-03-27.csv"))
gambia.getData()

                                  conception_date delivery_date village_name  \
f2a_participant_id exposure_month
220-10005          2019_01             2019-01-02    2019-10-17    Farafenni
                   2019_02             2019-01-02    2019-10-17    Farafenni
                   2019_03             2019-01-02    2019-10-17    Farafenni
                   2019_04             2019-01-02    2019-10-17    Farafenni
                   2019_05             2019-01-02    2019-10-17    Farafenni
...                                           ...           ...          ...
220-24838          2021_09             2021-05-08    2022-01-22     Katchang
                   2021_10             2021-05-08    2022-01-22     Katchang
                   2021_11             2021-05-08    2022-01-22     Katchang
                   2021_12             2021-05-08    2022-01-22     Katchang
                   2022_01             2021-05-08    2022-01-22     Katchang

                                  facility_name
f2a_participant_id exposure_month
220-10005          2019_01            Farafenni
                   2019_02            Farafenni
                   2019_03            Farafenni
                   2019_04            Farafenni
                   2019_05            Farafenni
...                                         ...
220-24838          2021_09             Illiassa
                   2021_10             Illiassa
                   2021_11             Illiassa
                   2021_12             Illiassa
                   2022_01             Illiassa

[10926 rows x 4 columns]

In [97]:
gambia.getData().to_csv(os.path.join(root_dir, "Gambia", "Gambia_women.csv"))

In [95]:
kenya=Precise('kenya', os.path.join(root_dir, "PRECISE_data_request_2024-03-27.csv"))
kenya.getData()

                                  conception_date delivery_date village_name  \
f2a_participant_id exposure_month
254-40004          2018_12             2018-12-17    2019-09-17      MWELE_B
                   2019_01             2018-12-17    2019-09-17      MWELE_B
                   2019_02             2018-12-17    2019-09-17      MWELE_B
                   2019_03             2018-12-17    2019-09-17      MWELE_B
                   2019_04             2018-12-17    2019-09-17      MWELE_B
...                                           ...           ...          ...
254-92532          2022_05             2021-12-03    2022-09-03     KINANI_B
                   2022_06             2021-12-03    2022-09-03     KINANI_B
                   2022_07             2021-12-03    2022-09-03     KINANI_A
                   2022_08             2021-12-03    2022-09-03     KINANI_A
                   2022_09             2021-12-03    2022-09-03     KINANI_A

                                  facility_name
f2a_participant_id exposure_month
254-40004          2018_12                Rabai
                   2019_01                Rabai
                   2019_02                Rabai
                   2019_03                Rabai
                   2019_04                Rabai
...                                         ...
254-92532          2022_05            Mariakani
                   2022_06            Mariakani
                   2022_07            Mariakani
                   2022_08            Mariakani
                   2022_09            Mariakani

[24686 rows x 4 columns]

In [96]:
kenya.getData().to_csv(os.path.join(root_dir, "Kenya", "Kenya_women.csv"))

## Unmapped Kenya villages
The workflow below was for identifying Kenya villages remaining unmapped after the Mombasa Precise Retreat

In [37]:
ke_villages=pd.concat([anc_data[['county_V1', 'KE_CHU_V1', 'KE_Village_V1']].rename(columns={'county_V1': 'county', 'KE_CHU_V1': 'chu', 'KE_Village_V1': 'village'}),\
                       anc_data[['county_V2', 'KE_CHU_V2', 'KE_Village_V2']].rename(columns={'county_V2': 'county', 'KE_CHU_V2': 'chu', 'KE_Village_V2': 'village'}),\
                       anc_data[['county_delivery', 'KE_CHU_delivery', 'KE_Village_delivery']].rename(columns={'county_delivery': 'county', 'KE_CHU_delivery': 'chu', 'KE_Village_delivery': 'village'})])
ke_villages=(ke_villages.groupby(by=['chu', 'village'])
             .count()
             .dropna()
             .rename(columns={'county':'women'})
             .reset_index())
ke_villages['village']=ke_villages['village'].apply(lambda x: x.replace('-', ' '))
ke_villages['village']=ke_villages['village'].apply(lambda x: x.replace('_', ' '))
ke_villages['chu']=ke_villages['chu'].apply(lambda x: x.replace('-', ' '))
ke_villages['chu']=ke_villages['chu'].apply(lambda x: x.replace('_', ' '))
ke_villages

          chu          village  women
0        BUNI            BONJE     67
1        BUNI   BUNI KIBAONI A    165
2        BUNI   BUNI KIBAONI B     32
3        BUNI   BUNI KISWARINI     75
4        BUNI          JITENGE      3
..        ...              ...    ...
94       RIBE         MAKOBENI      2
95  VISHAKANI         CHANDANI      3
96  VISHAKANI  KALOLENI CENTRE      6
97  VISHAKANI            NGOME      2
98  VISHAKANI        VISHAKANI      2

[99 rows x 3 columns]

In [38]:
ke_villages.to_csv('shapefiles/kenya_villages.csv')

In [32]:
import geopandas as gpd
kenya=gpd.read_file('shapefiles/precise_villages.gpkg', layer='kenya')

In [33]:
kenya

,village_code,name,chu,geometry
0,254001,BATANI,KOMBENI,"MULTIPOLYGON (((39.59833 -3.88683, 39.59846 -3..."
1,254002,BATANI ASILI,KOMBENI,"MULTIPOLYGON (((39.58833 -3.89329, 39.58847 -3..."
2,254003,BENGO MWARENI,MWELE KISURUTINI,"MULTIPOLYGON (((39.57167 -3.92821, 39.57178 -3..."
3,254004,BOFU,KOMBENI,"MULTIPOLYGON (((39.58083 -3.88951, 39.58096 -3..."
4,254005,BONJE,BUNI,"MULTIPOLYGON (((39.54833 -3.96975, 39.54845 -3..."
...,...,...,...,...
75,254070,SIMAKENI A,MWELE KISURUTINI,"MULTIPOLYGON (((39.56667 -3.92716, 39.56679 -3..."
76,254071,SIMAKENI B,MWELE KISURUTINI,"MULTIPOLYGON (((39.56000 -3.92486, 39.56014 -3..."
77,254072,TABORA,MWARENI,"MULTIPOLYGON (((39.47083 -3.86090, 39.47094 -3..."
78,254074,VIZIANI,KAMKOMANI,"MULTIPOLYGON (((39.52583 -3.88909, 39.52597 -3..."
79,254075,VUMA,SHANGIA,"MULTIPOLYGON (((39.41083 -3.81809, 39.41097 -3..."

In [50]:
kenya=kenya.drop_duplicates(subset=['chu', 'name'], keep='first')
kenya

,village_code,name,chu,geometry
0,254001,BATANI,KOMBENI,"MULTIPOLYGON (((39.59833 -3.88683, 39.59846 -3..."
1,254002,BATANI ASILI,KOMBENI,"MULTIPOLYGON (((39.58833 -3.89329, 39.58847 -3..."
2,254003,BENGO MWARENI,MWELE KISURUTINI,"MULTIPOLYGON (((39.57167 -3.92821, 39.57178 -3..."
3,254004,BOFU,KOMBENI,"MULTIPOLYGON (((39.58083 -3.88951, 39.58096 -3..."
4,254005,BONJE,BUNI,"MULTIPOLYGON (((39.54833 -3.96975, 39.54845 -3..."
...,...,...,...,...
75,254070,SIMAKENI A,MWELE KISURUTINI,"MULTIPOLYGON (((39.56667 -3.92716, 39.56679 -3..."
76,254071,SIMAKENI B,MWELE KISURUTINI,"MULTIPOLYGON (((39.56000 -3.92486, 39.56014 -3..."
77,254072,TABORA,MWARENI,"MULTIPOLYGON (((39.47083 -3.86090, 39.47094 -3..."
78,254074,VIZIANI,KAMKOMANI,"MULTIPOLYGON (((39.52583 -3.88909, 39.52597 -3..."
79,254075,VUMA,SHANGIA,"MULTIPOLYGON (((39.41083 -3.81809, 39.41097 -3..."

In [56]:
comb=kenya[['village_code', 'name', 'chu']].merge(ke_villages, left_on=['name', 'chu'], right_on=['village', 'chu'], how='right', validate='1:1')
comb[comb.village_code.isna()].sort_values(by='women', ascending=False).to_csv('shapefiles/kenya_unmapped.csv')

In [25]:
anc_data[anc_data.duplicated(keep=False)]

,f2a_participant_id,cohort,country,health_facility_v1,health_facility_v2,visit1_date,GA_PRECISE_V1,visit2_date,GA_PRECISE_V2,visit3_date,...,f2_ke_vlg_chalani,f2_ke_vlg_madzimbani,f2_ke_vlg_mwamleka,f2_ke_vlg_chilulu,f2_ke_vlg_makomboani,f2_ke_vlg_mikiriani,f2_ke_vlg_mwareni,f2_ke_vfg_other_name,f2_ke_vfg_other,f2_ke_vfg_dk
2025,254-41349,UNS,Kenya,Rabai,Rabai,19-Aug-19,21.809990,11-Oct-19,29.381418,31-Dec-19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026,254-41349,UNS,Kenya,Rabai,Rabai,19-Aug-19,21.809990,11-Oct-19,29.381418,31-Dec-19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2320,254-44294,UNS,Kenya,Rabai,Rabai,14-Jan-20,18.999998,NaN,NaN,30-Apr-20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2321,254-44294,UNS,Kenya,Rabai,Rabai,14-Jan-20,18.999998,NaN,NaN,30-Apr-20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2496,254-46046,UNS,Kenya,Rabai,Rabai,11-Mar-20,16.571428,NaN,NaN,07-Aug-20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6095,254-92122,UNS,Kenya,Mariakani,Mariakani,19-Jul-22,29.428572,21-Sep-22,38.571430,21-Sep-22,...,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN
6098,254-92154,UNS,Kenya,Mariakani,Mariakani,19-Jul-22,9.428572,NaN,NaN,10-Jan-23,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN
6099,254-92154,UNS,Kenya,Mariakani,Mariakani,19-Jul-22,9.428572,NaN,NaN,10-Jan-23,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN
6133,254-92507,UNS,Kenya,Mariakani,Mariakani,30-Aug-22,20.000000,26-Oct-22,28.142857,25-Dec-22,...,NaN,NaN,NaN,NaN,NaN,NaN,13.0,NaN,NaN,NaN
6134,254-92507,UNS,Kenya,Mariakani,Mariakani,30-Aug-22,20.000000,26-Oct-22,28.142857,25-Dec-22,...,NaN,NaN,NaN,NaN,NaN,NaN,13.0,NaN,NaN,NaN